### ISSUE TITLE
Finish the Blockchain.info Provider [$50]

### ISSUE THREAD

**Issue by ianpurton** [onchain/paper-wallet-spender#1]
The Blockchain.info provider is located here https://github.com/onchain/paper-wallet-spender/blob/master/src/onchain/providers/blockchaininfo_provider.cr

The push_tx method needs to be implemented. The current implementation is not correct. You can test it by sending any valid bitcoin transaction and see what message you get back from blockchain.info.

Also create a new method 

`get_all_balances(coin : CoinType, address : Array(String), set_rate = true)`

This should return the same results as get_balance but for each address. 

Blockchain.info provider a multi address call that let's you get balances for a bunch of addresses in one go. See documentation here. https://www.blockchain.com/en/api/blockchain_api

`https://blockchain.info/multiaddr?active=$address|$address`

Both the `push_t`x and `get_all_balances` methods need a test added to the `blockchaininfo_spec.cr`

There's a bounty for this issue https://www.bountysource.com/issues/60938673-finish-the-blockchain-info-provider

**Comment by ghost** [comment]
Hi Ian, I just wanted to let you know that both the `push_tx` and `get_all_balances` methods are complete and I will make a pull request once I have completed the test for each.

**Comment by ianpurton** [comment]
Great thanks.

**Comment by ghost** [comment]
I have made a [pulll request](https://github.com/onchain/paper-wallet-spender/pull/9l) for  Blockchain.info Provider

**Comment by ianpurton** [comment]
@ATJohnson solved this. Thanks.
